# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tfstate-demo-jenkins"
    dynamodb_table = "terraform_locking_table"
    encrypt        = true
    key            = "account/./terraform.tfstate"
    region         = "us-east-1"
  }
}
